kind: Deployment
apiVersion: apps/v1
metadata:
  name: laravel-echo-server
  labels:
    app: laravel-echo-server
spec:
  selector:
    matchLabels:
      name: laravel-echo-server
  replicas: 1
  revisionHistoryLimit: 10
  strategy: {}
  template:
    metadata:
        labels:
          name: laravel-echo-server
    spec:
      containers:
      - image: laravel-echo-server
        name: laravel-echo-server
        ports:
        - protocol: TCP
          containerPort: 6001
        resources: 
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        env:
          - name: ECHO_ALLOW_CORS
            value: "true"
          - name: ECHO_ALLOW_HEADERS
            value: '*'
          - name: ECHO_ALLOW_METHODS
            value: '*'
          - name: ECHO_ALLOW_ORIGIN
            value: '*'
          - name: ECHO_PROTOCOL
            value: http
          - name: ECHO_REDIS_HOST
            value: redis
          - name: ECHO_REDIS_PORT
            value: "6379"
          - name: LARAVEL_ECHO_SERVER_AUTH_HOST
            value: https://webhook
          - name: LARAVEL_ECHO_SERVER_HOST
            value: 0.0.0.0
          - name: LARAVEL_ECHO_SERVER_PORT
            value: "6001"
      restartPolicy: Always
status: {}
