apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - image: registry.redhat.io/rhscl/redis-5-rhel7
        name: redis
        resources: 
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
          - protocol: TCP
            containerPort: 6379
      restartPolicy: Always
status: {}