apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: webhook
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-echo-server
spec:
  selector:
    name: laravel-echo-server
  ports:
  - port: 6001
    targetPort: 6001