kind: Deployment
apiVersion: apps/v1
metadata:
  #annotations:
  labels:
    app: webhook
  name: webhook
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      name: webhook
  template:
    metadata:
      name: webhook
      labels:
        name: webhook
    spec:
      containers:
        - name: webhook
          image: docker-registry.default.svc:5000/qe-webhook/webhook.site
          imagePullPolicy: Always
          resources: 
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
          args:
          - php
          - artisan
          - queue:work
          - --daemon
          - --tries=3
          - --timeout=10
          env:
          - name: APP_DEBUG
            value: "true"
          - name: APP_ENV
            value: dev
          - name: APP_LOG
            value: errorlog
          - name: APP_URL
            value: http://localhost:8084
          - name: BROADCAST_DRIVER
            value: redis
          - name: CACHE_DRIVER
            value: redis
          - name: DB_CONNECTION
            value: sqlite
          - name: ECHO_HOST_MODE
            value: path
          - name: QUEUE_DRIVER
            value: redis
          - name: REDIS_HOST
            value: redis:6379
          - name: S6_READ_ONLY_ROOT
            value: "1"
      restartPolicy: Always
status: {}